### ISSUE TITLE
Export dataset ids in json format

### ISSUE THREAD

**Issue by johnfolly** [Cosmo-Tech/Babylon#129]
Can powerbi deploy-workspace export a the generated set of Report name and report Id ?

**Comment by o-reo** [comment]
Hey John, you should not assign tickets.

**Comment by o-reo** [comment]
Hi @johnfolly, do you mean exporting it in a file ?
We are thinking about generating macro run reports with such data.

**Comment by o-reo** [comment]
Merged a PR that adds macro reports
