### ISSUE TITLE
Add a config fill-template command to output data from datastore or configuration

### ISSUE THREAD

**Issue by johnfolly** [Cosmo-Tech/Babylon#146]
Hello,

At the end of a solution deployment, we maintain a main README that contains all the information related to the deployment. We want to automate the generation and update of this Markdown file. Do you think that it should be a Babylon command or not?

**Comment by johnfolly** [comment]
# Deployment output

This repository is {{ integrator }} manifest for  {{ project name }} . All documentation belonging to this repo is about {{ project name }}  configuration and  {{ project name }}  deployments.

## Useful link

| Description                       | Value | Comment |
| --------------------------------- | ----- | ------- |
| **Web app url**                   |       |         |
| **Swagger url**                   |       |         |
| **ADT url**                       |       |         |
| **ADX cluster**                   |       |         |
| **ADX database**                  |       |         |
| **Container registry**            |       |         |
| **Data integration function App** |       |         |
| **Data integration storage**      |       |         |
| **Event Hub name space**          |       |         |
| **Event Hub**                     |       |         |
| **Web app repository**            |       |         |
| **Static web app**                |       |         |
| **Power Bi Workspace**            |       |         |

## App registration

| Description                      | App registration name | Application ID | Comment |
| -------------------------------- | --------------------- | -------------- | ------- |
| **Swagger App registration**     |                       |                |         |
| **Platform App registration**    |                       |                |         |
| **Web app App registration**     |                       |                |         |
| **ADT network App registration** |                       |                |         |

## Workspace identification

| Description                  | Value | Comment |
| ---------------------------- | ----- | ------- |
| **Organization id**          |       |         |
| **Solution id**              |       |         |
| **Workspace Key**            |       |         |
| **Workspace Id**             |       |         |
| **Terraform Workspace name** |       |         |
| **PowerBi Workspace id**     |       |         |

## Solution identification

| Description        | Value | Comment |
| ------------------ | ----- | ------- |
| **Engine name**    |       |         |
| **Engine version** |       |         |

## Environnement identification

| Description          | Value | Comment |
| -------------------- | ----- | ------- |
| **Platform version** |       |         |
| **API Version**      |       |         |
| **AKS Version**      |       |         |
| **ARM Version**      |       |         |
| **Web app Version**  |

**Comment by o-reo** [comment]
will be released in 2.1.0
