### ISSUE TITLE
Defining coding standards

### ISSUE THREAD

**Issue by o-reo** [Cosmo-Tech/Babylon#26]
Following discussions with @lalepee and @neomatamune.
This issue will be updated as the project evolves.

### Development tools
- autoformatter: **yapf**
- linter: **flake8**

### Coding style standards
- column limit is 120
- one import per line
- prefer relative imports within the module

### Git hooks
You can put the following git hook in a file named ``.git/hooks/pre-commit`` to run checks before commit.
```bash
#!/bin/sh
flake8 .
yapf -r --diff .
pytest -v

**Comment by johnfolly** [comment]
This is my vscode workspace settings 

```json
{
    "python.sortImports.args": [
        "--trailing-comma",
        "--force-grid-wrap",
        "0",
        "--use-parentheses",
        "--force-single-line-imports",
        "--line-width",
        "88",
        "--multi-line",
        "3",
        "--float-to-top"
    ],
    "python.formatting.provider": "black",
    "python.formatting.blackArgs": [
        "--line-length=120"
    ],
    "editor.codeActionsOnSave": {
        "source.organizeImports": false
    },
    "python.linting.pylintArgs": [
        "--ignore=W1203",
    ]
}
```

**Comment by o-reo** [comment]
Hi @johnfolly  you should use YAPF instead of black, and flake8 instead of pylint, else your PR will be blocked (or you would have to do a lot of manual formatting).

**Comment by johnfolly** [comment]
Hello @o-reo,

I changed my settings to use yapf and flake8 👌

But I have some sugessions for yapf style 👇

```.style
#.style.yapf

[style]
based_on_style = google
column_limit = 120
indent_width: 4
dedent_closing_brackets: True
split_before_dot = True
split_before_logical_operator = True
coalesce_brackets = True
```

**Comment by johnfolly** [comment]
@o-reo , @lalepee , @neomatamune 
What do you think about ?

**Comment by o-reo** [comment]
I added optional git hooks to automate our local workflow ;)
