### ISSUE TITLE
ModuleNotFoundError: No module named 'git' on main

### ISSUE THREAD

**Issue by johnfolly** [Cosmo-Tech/Babylon#44]
### Missing git on babylon [main](https://github.com/Cosmo-Tech/Babylon/tree/main) requirements 

![image](https://user-images.githubusercontent.com/112887402/198249881-51b671dd-98bf-4636-8cc8-21d83402add3.png)

**Comment by neomatamune** [comment]
Read the infos on the commit : 
https://github.com/Cosmo-Tech/Babylon/commit/c66ba09832da5d7aea803c284d349117e7a9ea8b
