### ISSUE TITLE
Got traceback after No value found Error for babylon config key

### ISSUE THREAD

**Issue by johnfolly** [Cosmo-Tech/Babylon#75]
# Got traceback after No value found Error for babylon config key

## Description of current Behavior

When I tried to invoke a Babylon command which required a missing value from deployment or platform config I got a proper Error log with the error message and below this message I also got an error Traceback.

## Steps to Reproduce

- Install Babylon from main brach
- Run an api command without setup the api scope value in `config/deployments/deploy.yaml`

```bash
# Example
babylon api organization get-all
```

## Expected behavior

- When babylon encountered a missing value from only the error message should be displayed.
- The error message should be more explicit, I suggest :

> No value provided for the required key api_scope in platform config file.  
> api commands won't run without it.  
>Edit ~/babylon_config_path/config/platforms/platform.yaml

**Comment by neomatamune** [comment]
Deocrator used to not raise `KeyError` but `Click.Abort` which was captured differently.
