### ISSUE TITLE
Terraform cloud workspace create command do not write new workspace_id and and workspace_name

### ISSUE THREAD

**Issue by johnfolly** [Cosmo-Tech/Babylon#80]
# Terraform cloud workspace create command do not write new workspace_id and and workspace_name in terraform workspace config file

## Current behavior 

- `select` option do not have default value for the command `babylon terraform-cloud workspace create`
- the workspace_name is not persist by the select option

## Expected behavior 

- `select` option should be boolean option with default value = True
- the workspace_name should be also persist in terraform workspace config file

**Comment by neomatamune** [comment]
`select` is a flag option so if present it's value is `True` else it will be `False`
