### ISSUE TITLE
Format api scope and resolve suitable value for babylon

### ISSUE THREAD

**Issue by johnfolly** [Cosmo-Tech/Babylon#82]
# Format api scope and resolve suitable value for babylon

@jblanc-cosmotech suggested to auto format api scope from legacy format to a suitable value for babylon api command group.

## Current Behavior

- api_scope is a string value in platform config file
- babylon use this value as it is and to not apply any formatting
- common api scopes have `/something` suffix and cosmotech-api lib do not accept this format

## Expected behavior

- format api scope with a function ( or lambda), this function should be parsed to the require_platform_key decorator

````python
@require_platform_key("api_scope", "api_scope", formatter=api_scope_formatter)
```

**Comment by johnfolly** [comment]
What do you think about ? @o-reo , @neomatamune

**Comment by o-reo** [comment]
Is this still an issue ?
I am not certain to understand but it's seems to be an issue with cosmotech-api-lib ?

**Comment by johnfolly** [comment]
It an strange behavior of the api it self but. It no more an issue
